import Head from "next/head";

import ProductList from "@/components/ProductList";
import CateFilterButton from "@/components/CateFilterButton";
import { useState } from "react";

import styles from "../styles/Home.module.css";
import InterfaceFilterButton from "@/components/InterfaceFilterButton";
import List from "@/components/List";
import Order from "@/components/Order";

/* ----------------- TYPE DECLARATION ----------------- */
export type HandleCateChange = {
  handleCateChange: (value: string) => void;
};

export type handleInterfaceChange = {
  handleInterfaceChange: (value: string) => void;
};

export type Category = {
  category: string;
};
/* ----------------- TYPE DECLARATION ----------------- */

/* ================== MAIN COMPONENT ================== */
export default function Home() {
  const [category, setCategory] = useState("");
  const [appInterface, setAppInterface] = useState("New Order");

  function handleCateChange(category: string) {
    setCategory(category);
  }

  function handleInterfaceChange(appInterface: string) {
    setAppInterface(appInterface);
  }

  return (
    <>
      <Head>
        <title>Pet Food App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainContainer}>
        <div className={styles.container}>
          <List
            handleInterfaceChange={handleInterfaceChange}
            handleCateChange={handleCateChange}
            category={category}
          />
          <Order />
        </div>
      </main>
    </>
  );
}

{
  /*<div className={styles.container}>*/
}
{
  /*  <InterfaceFilterButton*/
}
{
  /*    handleInterfaceChange={handleInterfaceChange}*/
}
{
  /*  />*/
}
{
  /*  <h4>Category</h4>*/
}
{
  /*  <CateFilterButton handleCateChange={handleCateChange} />*/
}
{
  /*  <h4>Products</h4>*/
}
{
  /*  <ProductList category={category} />*/
}
{
  /*</div>*/
}
