import Head from "next/head";

import React, { useState } from "react";

import styles from "../styles/Home.module.css";
import ListSection from "@/components/ListSection";
import OrderSection from "@/components/OrderSection";
import { useOrderStore } from "@/stores/OrderStore";
import ConfirmEditModal from "@/components/ConfirmEditModal";

/* ----------------- TYPE DECLARATION ----------------- */
export type HandleCateChange = {
  handleCateChange: (value: string) => void;
};

export type handleInterfaceChange = {
  handleInterfaceChange: (value: string) => void;
};

/* ----------------- TYPE DECLARATION ----------------- */

/* ================== MAIN COMPONENT ================== */
export default function Home() {
  const [appInterface, setAppInterface] = useState("New Order");
  const clearCurrentOrder = useOrderStore((state) => state.clearCurrentOrder);

  function handleInterfaceChange(interfaceValue: string) {
    clearCurrentOrder();
    setAppInterface(interfaceValue);
  }

  return (
    <>
      <Head>
        <title>Pet Food App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainContainer}>
        <div className={styles.container}>
          <ListSection
            appInterface={appInterface}
            handleInterfaceChange={handleInterfaceChange}
          />
          <OrderSection appInterface={appInterface} />
        </div>
      </main>
    </>
  );
}
